// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP6uIRpjkMts78dw_JlMsoZnlwGYDGygk',
    appId: '1:619524649230:web:24718b727a378d982de75f',
    messagingSenderId: '619524649230',
    projectId: 'appplant-be1d0',
    authDomain: 'appplant-be1d0.firebaseapp.com',
    storageBucket: 'appplant-be1d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDub46j6hdExTOdAnpGK3IYXnNadJ8CTd0',
    appId: '1:619524649230:android:1fc374380fd127d22de75f',
    messagingSenderId: '619524649230',
    projectId: 'appplant-be1d0',
    storageBucket: 'appplant-be1d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9tiNH8rjQP1-pr6BPE82REHoAqinQPkA',
    appId: '1:619524649230:ios:1a5f43db37cfa48d2de75f',
    messagingSenderId: '619524649230',
    projectId: 'appplant-be1d0',
    storageBucket: 'appplant-be1d0.firebasestorage.app',
    iosBundleId: 'com.example.appPlant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9tiNH8rjQP1-pr6BPE82REHoAqinQPkA',
    appId: '1:619524649230:ios:1a5f43db37cfa48d2de75f',
    messagingSenderId: '619524649230',
    projectId: 'appplant-be1d0',
    storageBucket: 'appplant-be1d0.firebasestorage.app',
    iosBundleId: 'com.example.appPlant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP6uIRpjkMts78dw_JlMsoZnlwGYDGygk',
    appId: '1:619524649230:web:d155fd3e61e34c792de75f',
    messagingSenderId: '619524649230',
    projectId: 'appplant-be1d0',
    authDomain: 'appplant-be1d0.firebaseapp.com',
    storageBucket: 'appplant-be1d0.firebasestorage.app',
  );
}